DATA_TYPE = [
    'bool',
    'int',
    'short int',
    'long int',
    'long long int',
    'float',
    'double',
    'long double',
    'char',
    'unsigned char',
    'signed char',
    'unsigned short',
    'unsigned int',
    'unsigned long int',
    'unsigned long long int',
    'void'
]

KEYWORDS = {
    'for': 'cycle',
    'while': 'cycle',
    'do': 'cycle',
    '#include': 'preprocessor',
    'if': 'conditional',
    'else': 'conditional',
    'return': 'keyword',
    'void': 'data type',
    'struct': 'keyword',
    'union': 'keyword',
    'enum': 'keyword',
    'typedef': 'keyword',
    'const': 'modifier',
    'static': 'modifier',
    'extern': 'modifier',
    'volatile': 'modifier',
    'switch': 'conditional',
    'case': 'conditional',
    'default': 'conditional',
    'break': 'keyword',
    'continue': 'keyword',
    'sizeof': 'operator',
    'printf': 'operator',
}

SYMBOLS = {
    '(': 'PARENTHESIS',
    ')': 'PARENTHESIS',
    '{': 'BRACE',
    '}': 'BRACE',
    '[': 'BRACKET',
    ']': 'BRACKET',
    ';': 'SEMICOLON',
    ',': 'COMMA',
    '=': 'OPERATOR',
    '+': 'OPERATOR',
    '-': 'OPERATOR',
    '*': 'OPERATOR',
    '/': 'OPERATOR',
    '%': 'OPERATOR',
    '&&': 'LOGICAL_OPERATOR',
    '||': 'LOGICAL_OPERATOR',
    '!': 'LOGICAL_OPERATOR',
    '==': 'COMPARISON_OPERATOR',
    '!=': 'COMPARISON_OPERATOR',
    '<': 'COMPARISON_OPERATOR',
    '>': 'COMPARISON_OPERATOR',
    '<=': 'COMPARISON_OPERATOR',
    '>=': 'COMPARISON_OPERATOR',
    '&': 'BITWISE_OPERATOR',
    '|': 'BITWISE_OPERATOR',
    '^': 'BITWISE_OPERATOR',
    '~': 'BITWISE_OPERATOR',
    '<<': 'BITWISE_OPERATOR',
    '>>': 'BITWISE_OPERATOR',
    '->': 'ACCESS_OPERATOR',
    '.': 'ACCESS_OPERATOR',
    '++': 'INCREMENT_OPERATOR',
    '--': 'DECREMENT_OPERATOR',
    '//': 'SINGLE LINE COMMENT',
    '/*': 'MULTILINE COMMENT START',
    '*/': 'MULTILINE COMMENT END'
}

